<a href="https://colab.research.google.com/github/justincobelens/learning_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

### Creating tensors

`torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [13]:
# Scalar
scalar = torch.tensor(7)
scalar

# Get tensor back as Python int
scalar.item()

7

In [14]:
# Vector 
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [18]:
# MATRIX 
MATRIX = torch.tensor([[7,7,7], [7,7,7]])
MATRIX
MATRIX.ndim
MATRIX[0][0].item()

7

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape


torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way many neural networks learn is thatthey start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [34]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3652, 0.7194, 0.6480, 0.0427],
        [0.5295, 0.8122, 0.5681, 0.4593],
        [0.9957, 0.7331, 0.9380, 0.8844]])

In [36]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [39]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [48]:
# Use torch.arange()
zero_to_four = torch.arange(0, 4)
zero_to_four

tensor([0, 1, 2, 3])

In [49]:
# Create tensors like
four_zeros = torch.zeros_like(input=zero_to_four)
four_zeros

tensor([0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [58]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None,  # 'cuda' for gpu, 'cpu' for cpu 
                               requires_grad=False)  # wheter or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [60]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [63]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [64]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting infomation from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [66]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4784, 0.0483, 0.7490, 0.9073],
        [0.7553, 0.6651, 0.6411, 0.4793],
        [0.0197, 0.4866, 0.4327, 0.4897]])

In [69]:
# Find out details about some tensor (tensor attributes)
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # .size() is a function that similar to .shape
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4784, 0.0483, 0.7490, 0.9073],
        [0.7553, 0.6651, 0.6411, 0.4793],
        [0.0197, 0.4866, 0.4327, 0.4897]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulation Tensors (tensor operations)


Tensor operatiosn inclucde:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [3]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [4]:
# Multiply tensor
tensor * 10

tensor([10, 20, 30])

In [5]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [6]:
# PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [7]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [8]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix multiplication

2 main ways of performing multiplication in neural networks and deep learning:

1. Element-wise main
2. Matrix multiplication

Thre are 2 main rules that performing matrix mp needs to satisfy:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [9]:
# element wise mp

tensor*tensor

tensor([1, 4, 9])

In [11]:
# matrix mp
torch.matmul(tensor, tensor)

tensor(14)

In [12]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.23 ms, sys: 0 ns, total: 4.23 ms
Wall time: 7.97 ms


In [13]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.14 ms, sys: 0 ns, total: 1.14 ms
Wall time: 2.82 ms


tensor(14)

### One of the most common errors in DL: shape errors

In [20]:
# Shape for matrix mp
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is torch.matmul is @


RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of on of the tensors useing a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor

In [21]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [22]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregation)

In [23]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [24]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [25]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [28]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [29]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min/max

In [31]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Find the pos in tensor that has the min value with `argmin()` -> returns index of tensor where the min occurs
x.argmin()

tensor(0)

In [33]:
y = torch.tensor([1, 4, 0, 3, 5])
y.argmin()

tensor(2)

In [35]:
# Find th epos in tensor that has the max value with `argmax()` -> returns index of tensor where the max occurs
y.argmax()

tensor(4)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a cerain shape but keep the same memory as the orginial tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensors
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [45]:
# Create a tensor
import torch

x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [48]:
# Add an extra dim
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [49]:
x_reshaped = x_reshaped.reshape(1, 10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [59]:
# Change the view
x = torch.arange(1., 10.)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z change x (because a view of a tensor shares the same memory as t he orginal input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
z, z[:], z[0], z[0, :], z[:, 0]

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([5.]))

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [83]:
# Squeeze tensors, torch.squeeze() - removes all single dim from a target tensor
y = torch.zeros(2, 1, 2, 1, 2)
y_squeeze = torch.squeeze(y)
print(f"Original Tensor: {y.size()}")
print(f"\nSqueezed Tensor: {y_squeeze.shape}")


Original Tensor: torch.Size([2, 1, 2, 1, 2])

Squeezed Tensor: torch.Size([2, 2, 2])


In [89]:
# torch.unsqueeze() - adds a single dim to a target tensor at a specific dim
y_unsqueeze = y_squeeze.unsqueeze(dim=1)
print(f"Unsqueezed Tensor {y_unsqueeze.size()}")
y_unsqueeze

Unsqueezed Tensor torch.Size([2, 1, 2, 2])


tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])

In [92]:
# torch.permute - rearrange the dim of a target tensor in a specified order
x_original = torch.rand(size=(3, 223, 224))  # [colour_channels, height, width]

# permute the original tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute(1, 2, 0)  # shifts axis 0->2 1->2 2->0

x_original.shape, x_permuted.shape  # [height, width, colour_channels]

(torch.Size([3, 223, 224]), torch.Size([223, 224, 3]))

In [94]:
x_original[0][0][0] = 1
x_original[0][0][0], x_permuted[0][0][0]

(tensor(1.), tensor(1.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [95]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [96]:
# Index on tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
# Index on middle bracket (dim=1)
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [99]:
# index on last inner bracket
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [101]:
# ":" to select "all" of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [102]:
# Get all values of 0th and 1th dim but only index 1 of 2nd dim
x[:, :, 1] 

tensor([[2, 5, 8]])

In [115]:
x[:, :2, 1], x[0, :2, 1]

(tensor([[2, 5]]), tensor([2, 5]))

## PyTorch tensors & NumPy

NumPy is a popupar scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy 0> `torch.Tensor.numpy()`

**Note**: They don't share memory

In [120]:
# NumPy array to tensor
import torch
import numpy as np

arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr) # add .type(torch.float32) for float32 datatype
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [121]:
arr.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [122]:
# Change the value of the arr
arr = arr + 1
arr, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [124]:
# Tensor to NumPy arr
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [125]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random number to try an make them better representations of the data -> again -> again ...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


https://pytorch.org/docs/stable/notes/randomness.html

In [137]:
import torch

# Create 2 rand tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
random_tensor_A == random_tensor_B


tensor([[0.6559, 0.2280, 0.0747, 0.2927],
        [0.8358, 0.7054, 0.8463, 0.7653],
        [0.9429, 0.9075, 0.0501, 0.1609]])
tensor([[0.0929, 0.1792, 0.6060, 0.2868],
        [0.1019, 0.7593, 0.1870, 0.1179],
        [0.6514, 0.9994, 0.9858, 0.1791]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [139]:
# You have to keep setting manual seed per use

SEED = 42

torch.manual_seed(SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scene to make everything good.

### 1. Getting a GPU

1. Use Google Colab
2. Use own GPU
3. Use cloud computing - GCP, AWS, Azure

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, refer to PyTorch setup docs

https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Tue Mar 14 14:22:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    28W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on GPU or CPU, it's best practice to setup device agnositc code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices



In [3]:
# Setup device agnositc code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [5]:
# Create a tensors (default on the CPU)
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transorm it to NumPy
tensors_on_gpu.numpy()

NameError: ignored

In [11]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu

<function Tensor.numpy>

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')