<a href="https://colab.research.google.com/github/justincobelens/learning_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

### Creating tensors

`torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [13]:
# Scalar
scalar = torch.tensor(7)
scalar

# Get tensor back as Python int
scalar.item()

7

In [14]:
# Vector 
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [18]:
# MATRIX 
MATRIX = torch.tensor([[7,7,7], [7,7,7]])
MATRIX
MATRIX.ndim
MATRIX[0][0].item()

7

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.ndim
TENSOR.shape


torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way many neural networks learn is thatthey start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [34]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3652, 0.7194, 0.6480, 0.0427],
        [0.5295, 0.8122, 0.5681, 0.4593],
        [0.9957, 0.7331, 0.9380, 0.8844]])

In [36]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [39]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [48]:
# Use torch.arange()
zero_to_four = torch.arange(0, 4)
zero_to_four

tensor([0, 1, 2, 3])

In [49]:
# Create tensors like
four_zeros = torch.zeros_like(input=zero_to_four)
four_zeros

tensor([0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [58]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None,  # 'cuda' for gpu, 'cpu' for cpu 
                               requires_grad=False)  # wheter or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [60]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [63]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [64]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting infomation from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [66]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4784, 0.0483, 0.7490, 0.9073],
        [0.7553, 0.6651, 0.6411, 0.4793],
        [0.0197, 0.4866, 0.4327, 0.4897]])

In [69]:
# Find out details about some tensor (tensor attributes)
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # .size() is a function that similar to .shape
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4784, 0.0483, 0.7490, 0.9073],
        [0.7553, 0.6651, 0.6411, 0.4793],
        [0.0197, 0.4866, 0.4327, 0.4897]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulation Tensors (tensor operations)
